
include::onecx-data-orchestrator-bff-attributes.adoc[opts=optional]

=== Default properties

.{properties-file}
[%collapsible%open]
====
[source,properties,subs=attributes+]
----
quarkus.http.auth.permission.health.paths=/q/*
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated
onecx.permissions.application-id=${quarkus.application.name}
onecx.permissions.product-name=onecx-data-orchestrator
quarkus.kubernetes-client.trust-certs=true
%prod.quarkus.oidc-client.client-id=${ONECX_OIDC_CLIENT_CLIENT_ID:${quarkus.application.name}}
onecx.data.orchestrator.types.data.enabled=true
onecx.data.orchestrator.types.data.value=Data
onecx.data.orchestrator.types.database.enabled=true
onecx.data.orchestrator.types.database.value=Database
onecx.data.orchestrator.types.keycloak-client.enabled=true
onecx.data.orchestrator.types.keycloak-client.value=KeycloakClient
onecx.data.orchestrator.types.microfrontend.enabled=true
onecx.data.orchestrator.types.microfrontend.value=Microfrontend
onecx.data.orchestrator.types.microservice.enabled=true
onecx.data.orchestrator.types.microservice.value=Microservice
onecx.data.orchestrator.types.parameter.enabled=true
onecx.data.orchestrator.types.parameter.value=Parameter
onecx.data.orchestrator.types.permission.enabled=true
onecx.data.orchestrator.types.permission.value=Permission
onecx.data.orchestrator.types.product.enabled=true
onecx.data.orchestrator.types.product.value=Product
onecx.data.orchestrator.types.slot.enabled=true
onecx.data.orchestrator.types.slot.value=Slot
----
====

=== Extensions

include::onecx-data-orchestrator-bff-extensions.adoc[opts=optional]

=== Container

{docker-registry}[Docker registry]


=== Helm

{helm-registry}[Helm registry]

Default values

.{helm-file}
[source,yaml]
----
app:
  serviceAccount:
    enabled: true
  name: bff
  template:
    oidc_client_id: "ONECX_OIDC_CLIENT_CLIENT_ID"
  image:
    repository: "onecx/onecx-data-orchestrator-bff"
  envCustom:
    - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          crd:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            touch: permission on PUT request, where a resource is touched
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-pm:read ]
    microservice:
      spec:
        description: OneCX Data Orchestrator Backend for Frontend
        name: OneCX Data Orchestrator BFF
----

c.client.reactive.filter.OidcClientRequestReactiveFilter
%prod.quarkus.rest-client.onecx_announcement_v1.providers=io.quarkus.oidc.client.reactive.filter.OidcClientRequestReactiveFilter
%prod.quarkus.oidc-client.client-id=${quarkus.application.name}
----
====

=== Extensions

include::onecx-welcome-bff-extensions.adoc[opts=optional]

=== Container

{docker-registry}[Docker registry]


=== Helm

{helm-registry}[Helm registry]

Default values

.{helm-file}
[source,yaml]
----
app:
  name: bff
  image:
    repository: "onecx/onecx-welcome-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          image:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            delete: permission on all DELETE requests
          announcement:
            read: permission on all GET requests and POST search
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-wc:all, ocx-pm:read, ocx-an:read ]
----

